# =============================================================================
# SunnyLabX - Communication Stack
# Node: goingmerry (Node #2)
# Category: Communication & Collaboration
# =============================================================================
# Services: Matrix Synapse, Element Web, PostgreSQL (Matrix)
# Purpose: Encrypted messaging and real-time communication
# Network: Dedicated communication network with database backend
# =============================================================================

services:
  # PostgreSQL for Matrix Synapse
  matrix-postgres:
    image: postgres:16-alpine
    container_name: matrix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${MATRIX_DB_NAME:-synapse}
      POSTGRES_USER: ${MATRIX_DB_USER:-synapse}
      POSTGRES_PASSWORD: ${MATRIX_DB_PASSWORD:-changeme}
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - matrix_postgres_data:/var/lib/postgresql/data
    networks:
      - matrix_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MATRIX_DB_USER:-synapse}"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=false"

  # Redis for Matrix Synapse caching
  matrix-redis:
    image: redis:7-alpine
    container_name: matrix-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - matrix_redis_data:/data
    networks:
      - matrix_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=false"

  # Matrix Synapse - Federated messaging server
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix-synapse
    restart: unless-stopped
    environment:
      SYNAPSE_CONFIG_DIR: /data
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
      UID: ${MATRIX_UID:-991}
      GID: ${MATRIX_GID:-991}
      TZ: ${TZ:-UTC}
    volumes:
      - synapse_data:/data
      - ./synapse/homeserver.yaml:/data/homeserver.yaml:ro
      - ./synapse/log.config:/data/log.config:ro
    ports:
      - "8008:8008"
      - "8448:8448"  # Federation port
    networks:
      - matrix_network
    depends_on:
      - matrix-postgres
      - matrix-redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matrix.rule=Host(`matrix.lab.local`)"
      - "traefik.http.services.matrix.loadbalancer.server.port=8008"
      - "traefik.http.routers.matrix-federation.rule=Host(`matrix.lab.local`) && PathPrefix(`/_matrix/`)"
      - "traefik.http.services.matrix-federation.loadbalancer.server.port=8448"

  # Element Web - Matrix web client
  element-web:
    image: vectorim/element-web:latest
    container_name: element-web
    restart: unless-stopped
    volumes:
      - ./element/config.json:/app/config.json:ro
    ports:
      - "8080:80"
    networks:
      - matrix_network
    depends_on:
      - synapse
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.element.rule=Host(`chat.lab.local`)"
      - "traefik.http.services.element.loadbalancer.server.port=80"

  # Matrix Admin - Administration interface
  matrix-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: matrix-admin
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - matrix_network
    depends_on:
      - synapse
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matrix-admin.rule=Host(`matrix-admin.lab.local`)"
      - "traefik.http.services.matrix-admin.loadbalancer.server.port=80"

  # Sliding Sync Proxy - Enhanced Matrix sync
  sliding-sync:
    image: ghcr.io/matrix-org/sliding-sync:latest
    container_name: matrix-sliding-sync
    restart: unless-stopped
    environment:
      SYNCV3_SERVER: http://synapse:8008
      SYNCV3_DB: "postgresql://${MATRIX_DB_USER:-synapse}:${MATRIX_DB_PASSWORD:-changeme}@matrix-postgres/${MATRIX_DB_NAME:-synapse}?sslmode=disable"
      SYNCV3_SECRET: ${SLIDING_SYNC_SECRET:-changeme}
    ports:
      - "8009:8008"
    networks:
      - matrix_network
    depends_on:
      - synapse
      - matrix-postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sliding-sync.rule=Host(`sync.lab.local`)"
      - "traefik.http.services.sliding-sync.loadbalancer.server.port=8008"

networks:
  matrix_network:
    driver: bridge
    name: matrix_network

volumes:
  matrix_postgres_data:
    driver: local
  matrix_redis_data:
    driver: local
  synapse_data:
    driver: local